### ISSUE TITLE
Add BRBL wordmark to footer

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/neural-neighbors#7]
Mike Morand was able to shoot me a vector version of their wordmark, which I placed in Dropbox/MK-viz/BRBL-branding/ .  Could we add this to the footer in some way? (Are there rules for lining up two wordmarks....?)

**Comment by ghost** [comment]
Here are the two footer options that we have:

<img width="684" alt="screenshot 2017-09-05 09 56 02" src="https://user-images.githubusercontent.com/25487/30064802-dca664a4-9220-11e7-997c-b21115228206.png">

<img width="1026" alt="screenshot 2017-09-05 09 58 15" src="https://user-images.githubusercontent.com/25487/30064807-df0cfe9c-9220-11e7-95c5-a989dc655e26.png">

Generally, it's best to have one distinct word mark and express partners in text.

**Comment by duhaime** [comment]
@pleonard212 @mongmedia I'd prefer the former, as it feels less cramped...

**Comment by pleonard212** [comment]
OK! We have another vote for the wordmark (1) from BRBL. Could we do the BRBL word mark, with the small text from 2?

**Comment by duhaime** [comment]
Sure thing--@mongmedia could you drop an uncompressed svg graphic of Beinecke's logo here? The strokes should be `path` elements so the font is "burned into" the graphic, rather than loaded by css.

**Comment by pleonard212** [comment]
Looks great, thanks!
