### ISSUE TITLE
Add Untitled for uncaptioned pics

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/neural-neighbors#8]
Because the title area is where we display similarity metrics, it might make sense to give a default title when none exists. (Right now, uncaptioned pictures don't display a title area at all, and thus show no similarity metric.)

We could try _Untitled_ (in italics), since we're already using brackets to indicate the similarity metric. OTOH, I know @mongmedia has thoughts about possibly using a darker text color for the metric %, which would free up brackets for use, so open to all ideas...

**Comment by duhaime** [comment]
That sounds good. Here are a few options:

![screen shot 2017-08-31 at 9 38 47 am](https://user-images.githubusercontent.com/4801116/29926054-4858b48a-8e30-11e7-8095-be6d543649e6.png)

![screen shot 2017-08-31 at 9 37 00 am](https://user-images.githubusercontent.com/4801116/29926055-48be5042-8e30-11e7-85fb-345339d497ad.png)

![screen shot 2017-08-31 at 9 37 18 am](https://user-images.githubusercontent.com/4801116/29926048-461c8f52-8e30-11e7-99dd-a64a5f7e383e.png)

**Comment by ghost** [comment]
<img width="259" alt="screenshot 2017-09-05 09 38 03" src="https://user-images.githubusercontent.com/25487/30063844-f9d0ba6e-921d-11e7-85f0-96ff596f8cb3.png">

Hello! I would try the percentage w/ a different color (#8D8D8D) and no need for the brackets. For the images without captions, "untitled" is OK. I'd also nudge the bar up a couple pixels.
